// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owqgzsoljtpxmelrpdxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93cWd6c29sanRweG1lbHJwZHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjY1NDUsImV4cCI6MjA2NDg0MjU0NX0.U0Z6sOeGA1grgFDP3x6SOmO8qInTWoBHIDrt0h1GFc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);